# Define the exports for the prx
PSP_BEGIN_EXPORTS

PSP_EXPORT_START(syslib, 0, 0x8000)
PSP_EXPORT_FUNC(module_start)
PSP_EXPORT_VAR_HASH(module_info)
PSP_EXPORT_END

PSP_EXPORT_START(SystemCtrlForUser, 0, 0x4001)
PSP_EXPORT_FUNC(sctrlHENSetStartModuleHandler)
PSP_EXPORT_END

PSP_EXPORT_START(SystemCtrlForKernel, 0, 0x0001)
PSP_EXPORT_FUNC(sctrlHENSetStartModuleHandler)
PSP_EXPORT_FUNC_NID(PatchSyscall, 0x826668E9)
PSP_EXPORT_END

PSP_END_EXPORTS
